SHELL := /bin/bash


doc:
	$(MAKE) doc -C ./Esterni/AdR
	$(MAKE) doc -C ./Esterni/DdP
	$(MAKE) doc -C ./Esterni/glossario
	$(MAKE) doc -C ./Esterni/PdP
	$(MAKE) doc -C ./Esterni/PdQ
	$(MAKE) doc -C ./Interni/NdP
	$(MAKE) doc -C ./Interni/SdF
	$(MAKE) doc -C ./lettera


clean:
	$(MAKE) clean -C ./Esterni/AdR
	$(MAKE) clean -C ./Esterni/DdP
	$(MAKE) clean -C ./Esterni/glossario
	$(MAKE) clean -C ./Esterni/PdP
	$(MAKE) clean -C ./Esterni/PdQ
	$(MAKE) clean -C ./Interni/NdP
	$(MAKE) clean -C ./Interni/SdF
	$(MAKE) clean -C ./lettera
